# Author : Francesco Seccamonte
# Copyright (c) 2022 Francesco Seccamonte. All rights reserved.  
# Licensed under the Apache 2.0 License. See LICENSE file in the project root for full license information.  
# 

sudo: required
language: cpp

services:
  - docker

addons:
  apt:
    packages:
      # Update docker version
      - docker-ce

env:
  # used to setup a build matrix
  - BUILD_TYPE=Debug
  - OS=ubuntu18.04
  - COMPILER=gcc9
  - COMPILER=gcc10
  - COMPILER=gcc11
  - COMPILER=gcc12
  - COMPILER=clang13
  - COMPILER=clang14

before_install:
  # Pull image
  - docker pull conanio/$COMPILER-$OS
  # Start container
  - docker run -itd --name build$COMPILER -v $TRAVIS_BUILD_DIR:/home/conan/repo conanio/$COMPILER
  # Configure conan
  - docker exec build$COMPILER conan profile update settings.compiler.libcxx=libstdc++11 default
  - docker exec build$COMPILER conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
  - docker exec build$COMPILER conan config set general.revisions_enabled=1

script:
  - docker exec build$COMPILER mkdir /home/conan/repo/build$COMPILER
  - docker exec -w /home/conan/repo/build$COMPILER build$COMPILER conan install -o cpp-travis-integration:build_tests=True --build=missing ..
  - docker exec -w /home/conan/repo/build$COMPILER build$COMPILER cmake -S .. -B . -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - docker exec -w /home/conan/repo/build$COMPILER build$COMPILER cmake --build .
  - docker exec -w /home/conan/repo/build$COMPILER build$COMPILER ctest --parallel

after_success:
  # Create a conan package containing the project
  - docker exec -w /home/conan/repo build$COMPILER conan create . francesco/testing
